apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frr-k8s
    app.kubernetes.io/instance: frr-k8s-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: frr-k8s
  name: frr-k8s-daemon
  namespace: frr-k8s-system
