[main]
summary=Optimized for running low latency workloads on MicroShift
include=cpu-partitioning

[variables]
include=/etc/tuned/microshift-baseline-variables.conf

[bootloader]
cmdline_microshift=+default_hugepagesz=${hugepagesDefaultSize} hugepagesz=2M hugepages=${hugepages2M} hugepagesz=1G hugepages=${hugepages1G}
cmdline_additionalArgs=+"${additionalArgs}"
