apiVersion: v1
kind: ConfigMap
metadata:
  name: generic-device-plugin-config
data:
  config.yaml: |
    domain: device.microshift.io
    device:
      - name: serial
        groups:
          - paths:
              - path: /dev/ttyUSB*
          - paths:
              - path: /dev/ttyACM*
          - paths:
              - path: /dev/tty.usb*
          - paths:
              - path: /dev/cu.*
          - paths:
              - path: /dev/cuaU*
          - paths:
              - path: /dev/rfcomm*
      - name: video
        groups:
          - paths:
              - path: /dev/video0
      - name: fuse
        groups:
          - count: 5
            paths:
              - path: /dev/fuse
      - name: audio
        groups:
          - count: 5
            paths:
              - path: /dev/snd
      - name: capture
        groups:
          - paths:
              - path: /dev/snd/controlC0
              - path: /dev/snd/pcmC0D0c
          - paths:
              - path: /dev/snd/controlC1
                mountPath: /dev/snd/controlC0
              - path: /dev/snd/pcmC1D0c
                mountPath: /dev/snd/pcmC0D0c
          - paths:
              - path: /dev/snd/controlC2
                mountPath: /dev/snd/controlC0
              - path: /dev/snd/pcmC2D0c
                mountPath: /dev/snd/pcmC0D0c
          - paths:
              - path: /dev/snd/controlC3
                mountPath: /dev/snd/controlC0
              - path: /dev/snd/pcmC3D0c
                mountPath: /dev/snd/pcmC0D0c
    