name: Build hello-microshift
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 3 * * 0' # Weekly, 3:00 on Sunday

jobs:
  build:
    name: Build hello-microshift
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: hello-microshift
        tags: v1 ${{ github.sha }}
        archs: amd64, arm64
        containerfiles: |
          ./e2e/images/Containerfile.hello-microshift
        context: ./e2e/images/

    - name: Push to registry
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/pmatusza
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
